import type { Metadata } from "next";

import { cn } from "@/utils/utils";
import { SideBar } from "@/components";
import ExtendedSideBar from "@/components/elements/side-bar/ExtendedSideBar";
import Header from "@/components/elements/header/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={cn("bg-[#f5f5f5] flex h-screen overflow-hidden")}>
      <aside className="flex-[0.03] flex">
        <SideBar />
      </aside>
      <section className="">
        <ExtendedSideBar />
      </section>

      <main className="flex-1">
        <Header />
        {children}
      </main>
    </div>
  );
}
